
name: Windows Build

on:
  push:
    branches: [ testing-build ]
  pull_request:
    branches: [ testing-build ]


jobs:
  release:
    runs-on: windows-latests

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: pip install -r requirements.txt 