
name: Macos Build

on:
  push:
    branches: 
      - testing-build
  pull_request:
    branches: 
      - testing-build


jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1