
name: Macos Build

on:
  push:
    branches: 
      - development
  pull_request:
    branches: 
      - development


jobs:
  build:
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Installing dependencies
        run: pip3 install -r requirements.txt