
name: Windows Build

on:
  push:
    branches: 
      - testing-build
  pull_request:
    branches: 
      - testing-build


jobs:
  release:
    runs-on: windows-latest

    steps: 
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: src

      - uses: actions/setup-node@v1
        with:
          python-version: '3.7.10'
      - name: Install dependencies
        run: pip install -r requirements.txt