
name: Windows Build

on:
  push:
    branches: 
      - testing-build
  pull_request:
    branches: 
      - testing-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      
      - name: Upload a singe artifact
        uses: actions/upload-artifact@v2
        with:
          name: Minecraft-TeamB
          path: src/dist/windows

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: Minecraft-TeamB
          path: src/dist/windows

      - name: release
        uses: ncipollo/release-action@v1
      	with:
          artifacts: "Minecraft-TeamB.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}