
name: Windows Build

on:
  push:
    branches: 
      - testing-build
  pull_request:
    branches: 
      - testing-build

page_build:
release:
  types: [published, created, edited]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1